export default {
  SET_LOGIN_DATA: "SET_LOGIN_DATA",
  SET_OTP_DATA: "SET_OTP_DATA",
  SET_USER_DATA: "SET_USER_DATA",
  SET_CURRENT_THEME: "SET_CURRENT_THEME",
  SET_RECENTLY_PLAYED: "SET_RECENTLY_PLAYED",
  ON_LOGOUT: "ON_LOGOUT",
};
